운동 목록 페이지 초기 퍼블리싱 입니다.
DogGae/Push-Up-Master pull request #19
Opened 2023-04-03 10:27 UTC by GoodSilver9

2023-04-04 14:32 UTC, swon3210 requested changes

2023-04-04 14:32 UTC, swon3210 commented on health_list/health_list.html
> +      <div class="addhealth">운동 추가하기</div>
운동 추가하기 버튼은 button 태그로 만들어주세요. 버튼 요소를 div 태그로 만드는 것은 웹 표준과 웹 접근성 측면에서 좋지 않은 마크업을 작성하는 것입니다. 자세한 내용은 아래 영상을 참고해보세요.

https://www.youtube.com/watch?v=xToJhmAJYCE

2023-04-04 14:32 UTC, swon3210 commented on health_list/health_list.html
> +            <img class="remove" src="/img/Remove.png" alt="Remove" />
삭제 기능 또한 클릭해서 동작하는 '버튼'을 통해 동작하는 것이기 때문에 이 삭제 아이콘 또한 단순히 img 태그가 아니라 button 태그로 감싸져 있어야 합니다.

2023-04-05 08:47 UTC, GoodSilver9 commented on health_list/health_list.html
> +      <div class="addhealth">운동 추가하기</div>
수정했습니다.

2023-04-05 08:47 UTC, GoodSilver9 commented on health_list/health_list.html
> +            <img class="remove" src="/img/Remove.png" alt="Remove" />
수정했습니다.

2023-04-07 10:29 UTC, swon3210 approved these changes
수고하셨습니다.

2023-04-07 10:29 UTC, merged