초기 퍼블리싱 작업
DogGae/Push-Up-Master pull request #8
Opened 2023-03-22 15:02 UTC by GoodSilver9

2023-03-22 15:21 UTC, swon3210 commented on index.html
> +      <button class="push_up_button" onclick="startTimer()">완료</button>
```suggestion
      <button class="push_up_button">버튼</button>
```
동작하지 않는 자바스크립트 코드는 지워주세요

2023-03-22 15:21 UTC, swon3210 commented on index.html
> +      </div>
```suggestion
      <div id="display" class="remaining">00:00</div>
```
불필요한 div 입니다. 지워주세요

2023-03-22 15:21 UTC, swon3210 commented on index.css
> +  border: 1px solid gray;
border 가 있는 편이 좋다고 생각한 것 같지만 디자인 시안은 함부로 승인 없이 변경할 수 있는 것이 아닙니다. border 는 지워주세요.

2023-03-22 15:21 UTC, swon3210 commented on index.css
> +}
### 변경 전

![image](https://user-images.githubusercontent.com/32982670/226952084-bea92ea2-6d75-4033-8c8d-9465fcd275a4.png)

### 변경 후

![image](https://user-images.githubusercontent.com/32982670/226952636-1716dd88-4187-4721-b453-bcb2fa8d9cb6.png)

수평 가운데 정렬은 잘하셨습니다. 수직으로도 가운데 정렬이 되게 하기 위해 CSS 코드를 아래와 같이 추가해주세요.

```suggestion
html {
  height: 100%;
}
body {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
}
```

2023-03-22 15:22 UTC, swon3210 requested changes
전체적으로 잘 해주셨습니다. 조금의 수정사항만 반영해주세요

2023-03-23 04:25 UTC, GoodSilver9 commented on index.html
> +      <button class="push_up_button" onclick="startTimer()">완료</button>
수정했습니다.

2023-03-23 04:25 UTC, GoodSilver9 commented on index.html
> +      </div>
수정했습니다.

2023-03-23 04:25 UTC, GoodSilver9 commented on index.css
> +  border: 1px solid gray;
수정했습니다.

2023-03-23 04:25 UTC, GoodSilver9 commented on index.css
> +}
수정했습니다.

2023-03-23 15:43 UTC, swon3210 approved these changes
수고하셨습니다.

2023-03-23 15:43 UTC, merged