푸쉬업 마스터 타이머 기능구현
DogGae/Push-Up-Master pull request #9
Opened 2023-03-24 04:27 UTC by GoodSilver9

2023-03-24 16:14 UTC, swon3210 requested changes

2023-03-24 16:14 UTC, swon3210 commented on app.js
> +    }`;
삼항연산자를 연쇄적으로 사용하는 코드는 읽는 사람이 한눈에 파악하기 힘듭니다. if 조건문을 여러번 쓰는 것으로 바꿔주세요.

2023-03-26 15:00 UTC, swon3210 requested changes

2023-03-26 15:00 UTC, swon3210 commented on app.js
> +    }
해당 로직은 잘못된 로직입니다. 

min 가 10 이상이 되면 무조건 적으로 분 앞에 잘못된 시간이 표기됩니다.
수정바랍니다.

![image](https://user-images.githubusercontent.com/32982670/227784430-fd35de2c-2baa-47e3-94d8-70b5cf2d8f4c.png)

2023-03-26 15:06 UTC, GoodSilver9 commented on app.js
> +startTimer = () => {
수정했습니다.

2023-03-26 15:06 UTC, GoodSilver9 commented on app.js
> +    }`;
수정했습니다.

2023-03-27 01:44 UTC, GoodSilver9 commented on app.js
> +    }
수정했습니다.

2023-03-27 01:45 UTC, swon3210 approved these changes
수고하셨습니다.

2023-03-27 01:46 UTC, merged